Include full path to shaper graphs in output.
Guilouz/Creality-Helper-Script pull request #18
Opened 2024-06-21 02:03 UTC by ccdunder

This wasn't immediately obvious to me and I imagine it could save other folks some time hunting down these paths.

2024-11-04 07:06 UTC, probielodan requested changes

2024-11-04 07:06 UTC, probielodan commented on files/improved-shapers/improved-shapers.cfg
> +  RESPOND TYPE=command MSG="X Graph is now available at {y_png}."
```suggestion
  RESPOND TYPE=command MSG="Y Graph is now available at {y_png}."
```

2024-11-13 12:16 UTC, Guilouz commented
Done.

2024-11-13 12:16 UTC, closed without merging

2024-11-14 06:17 UTC, ccdunder commented
![image](https://github.com/user-attachments/assets/fc0823a9-5805-426c-83d5-19fb480c8561)